name: Android
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '**'

jobs:
  Build_Test-Linux-Android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Swift 6
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0.3"

    - name: Install Android SDK
      run: |
        cd ..
        wget -q https://github.com/finagolfin/swift-android-sdk/releases/download/6.0.3/swift-6.0.3-android-24-sdk.tar.xz
        tar xf swift-6.0.3-android-24-sdk.tar.xz
        cd GateEngine
    - name: Swift Version
      run: swift --version

    - name: Build using Swift
      run: swift build --destination ../swift-6.0.3-android-24-sdk/usr/swiftpm-android-aarch64.json -Xlinker -rpath -Xlinker \$ORIGIN/lib/swift/android
