name: HTML5
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '**'

jobs:
  Build_Test-macOS-WASI:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1"

    - name: Install SwiftWasm SDK
      run: |
        swift sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-6.1-RELEASE/swift-wasm-6.1-RELEASE-wasm32-unknown-wasi.artifactbundle.zip --checksum 7550b4c77a55f4b637c376f5d192f297fe185607003a6212ad608276928db992

    - name: Swift Version
      run: swift --version

    - name: Build for WASI
      run: swift build --swift-sdk wasm32-unknown-wasi
    
#    - name: Archive
#      uses: actions/upload-artifact@v3
#      if: always()
#      with:
#        name: Wasm Binary
#        path: .build/wasm32-unknown-wasi/**/*.wasm

#    TODO: Figure out how to make chrome default without a confirmation
#    - name: Make Chrome Default
#        run: open -a "Google Chrome" --args --make-default-browser
#    
#    - name: Test Secure Context
#        run: carton test --environment defaultBrowser --host localhost
