name: HTML5
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    paths:
    - 'Sources/**'
    - 'Tests/**'
    - 'Macros/**'
    - 'Dependencies/**'
    - 'Package.swift'
    - 'Package.resolved'
    - '.github/workflows/HTML5.yml'
  pull_request:
    branches:
    - '**'
    paths:
    - 'Sources/**'
    - 'Tests/**'
    - 'Macros/**'
    - 'Dependencies/**'
    - 'Package.swift'
    - 'Package.resolved'
    - '.github/workflows/HTML5.yml'

concurrency:
  group: html5-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build_Test-macOS-WASI:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v5

    - name: Install Carton
      run: brew install swiftwasm/tap/carton

    - name: Test Insecure Context
      run: carton test --environment defaultBrowser --host 127.0.0.1

#    - name: Archive
#      uses: actions/upload-artifact@v3
#      if: always()
#      with:
#        name: Wasm Binary
#        path: .build/wasm32-unknown-wasi/**/*.wasm

#    TODO: Figure out how to make chrome default without a confirmation
#    - name: Make Chrome Default
#        run: open -a "Google Chrome" --args --make-default-browser
#
#    - name: Test Secure Context
#        run: carton test --environment defaultBrowser --host localhost
