name: Windows
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '**'

jobs:
  Build_Test-Windows-Windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-6.2-release
          swift-build: 6.2-RELEASE
      - uses: actions/checkout@v3
      
      - name: Swift Version
        run: swift --version
      
      - name: Build
        run: swift build -v -Xlinker /VERBOSE
      - name: Test
        run: swift test -v -Xlinker /VERBOSE
